### ISSUE TITLE
sites not loading

### ISSUE THREAD

**Issue by peterdudfield** [openclimatefix/nowcasting#414]
## To Reproduce
1. Go to sites page
4. Doesnt load

## Expected behavior
should load

## Additional context
- there is some code, to stop sites always loading, this is done to stop unnecessary data being loaded

**Comment by braddf** [comment]
This should be fixed on all deployments now

**Comment by peterdudfield** [comment]
I'm still having issues on `https://dev.quartz.solar/` it tried to load the forecasts for no sites I think, but im not totaly sure

**Comment by peterdudfield** [comment]
![Screenshot 2023-10-12 at 11 09 12](https://github.com/openclimatefix/nowcasting/assets/34686298/4e31ea04-2b84-41c8-976e-029817730e2a)
